-- Sample patient data for testing
INSERT INTO patients (
    id,
    first_name,
    last_name,
    date_of_birth,
    gender,
    email,
    phone_number,
    address_line1,
    city,
    state,
    postal_code,
    country,
    status,
    organization_id,
    created_by_id,
    updated_by_id,
    created_at,
    updated_at
) VALUES (
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'John',
    'Doe',
    '1980-01-01',
    'male',
    'john.doe@example.com',
    '+1-555-555-0100',
    '123 Main St',
    'Anytown',
    'CA',
    '12345',
    'USA',
    'active',
    (SELECT id FROM organizations LIMIT 1),
    (SELECT id FROM users LIMIT 1),
    (SELECT id FROM users LIMIT 1),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
    'Jane',
    'Smith',
    '1985-02-15',
    'female',
    'jane.smith@example.com',
    '+1-555-555-0200',
    '456 Oak Ave',
    'Somewhere',
    'NY',
    '67890',
    'USA',
    'active',
    (SELECT id FROM organizations LIMIT 1),
    (SELECT id FROM users LIMIT 1),
    (SELECT id FROM users LIMIT 1),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
); 