name: Security Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    - name: Run HIPAA compliance checks
      run: |
        # Check for unencrypted PHI
        find . -type f -not -path "*/\.*" -exec grep -l "SSN\|DOB\|MRN" {} \;
        
        # Check for proper logging configuration
        find . -type f -name "*.py" -exec grep -l "print(" {} \;
        
        # Check for secure communication
        find . -type f -name "*.py" -exec grep -l "http://" {} \;

    - name: Run SonarCloud scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=healthcare-ivr
          -Dsonar.organization=healthcare-org
          -Dsonar.sources=.
          -Dsonar.python.coverage.reportPaths=backend/coverage.xml
          -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

    - name: Run CIS benchmark checks
      uses: aquasecurity/kube-bench@main
      with:
        config: cis-1.6

    - name: Run container security scan
      uses: anchore/scan-action@v3
      with:
        image: "healthcare-ivr-backend:latest"
        fail-build: true
        severity-cutoff: high

    - name: Run dependency audit
      run: |
        # Backend dependencies
        cd backend
        safety check
        
        # Frontend dependencies
        cd ../frontend
        npm audit

    - name: Run secrets scanning
      uses: gitleaks/gitleaks-action@v2
      env:
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

    - name: Generate security report
      if: always()
      run: |
        echo "# Security Scan Report" > security-report.md
        echo "## Scan Results" >> security-report.md
        echo "### Vulnerabilities Found" >> security-report.md
        cat trivy-results.txt >> security-report.md
        echo "### HIPAA Compliance Issues" >> security-report.md
        cat hipaa-scan.txt >> security-report.md
        echo "### Container Security Issues" >> security-report.md
        cat container-scan.txt >> security-report.md

    - name: Upload security report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: security-report.md

    - name: Send security report
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        text: |
          Security scan completed. Results available in artifacts.
          Critical issues found: ${{ steps.security-scan.outputs.critical }}
          High issues found: ${{ steps.security-scan.outputs.high }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 